#!/bin/bash


if [ "$(playerctl status)" = "Playing" ]; then
  title=`exec playerctl metadata xesam:title`
  artist=`exec playerctl metadata xesam:artist`
  album=`exec playerctl metadata xesam:album`
  if [ "$artist" = "Various" ]; then
    artist="";
    echo "  $title"
  else
    echo "%{F#fff} $title %{F#7f9} - $artist - %{F#3c7} ($album)"
  fi
else
  echo ""
fi
